
export const data =     [
      {  
        id: 1,
        titl: "Eloquent JavaScript, Second Edition",
        subtil: "A Modern Introduction to Programming",
        count:1,
        quantity:1,
        total:10,
        price:10,
        description: "Like it or not, JavaScript is everywhere these days-from browser to server to mobile-and now you, too, need to learn the language or dive deeper than you have. This concise book guides you into and through JavaScript, written by a veteran programmer who once found himself in the same position.",

        author: "Marijn Havereke" ,    
           published: "2014-12-14T00:00:00.000Z",
       publishr: "No Starch Press",
       pages:472,
       AddCartCondition:false,
       imagepath:process.env.PUBLIC_URL + '/book6.jpg',
       purchse:false,
       count:1,
       quantity:1,
       total:10,
       price:10,
       desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
       website:"http://eloquentjavascript.ne/"
    },
    {  
      id: 2,
      titl: "Eloquent JavaScript, Second Edition",
      subtil: "A Modern Introduction to Programming",
      count:1,
      quantity:1,
      total:10,
      price:10,author: "Marijn Havereke"   ,  
      description: "Take advantage of JavaScript's power to build robust web-scale or enterprise applications that are easy to extend and maintain. By applying the design patterns outlined in this practical book, experienced JavaScript developers will learn how to write flexible and resilient code that's easier-yes, easier-to work with as your code base grows.",

       published: "2014-12-14T00:00:00.000Z",
     publishr: "No Starch Press",
     pages:472,
     AddCartCondition:false,
     imagepath:process.env.PUBLIC_URL + '/book2.jpg',
     purchse:false,
     count:1,
     quantity:1,
     total:10,
     price:10,
     desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
     website:"http://eloquentjavascript.ne/"
  },
  {  
    id: 3,
    titl: "Eloquent JavaScript, Second Edition",
    subtil: "A Modern Introduction to Programming",
    count:1,
    quantity:1,
    total:10,
    price:10,author: "Marijn Havereke"  ,
    description: "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript.",
  
    published: "2014-12-14T00:00:00.000Z",
   publishr: "No Starch Press",
   pages:472,
   AddCartCondition:false,
   imagepath:process.env.PUBLIC_URL + '/book3.jpg',
   purchse:false,
   count:1,
   quantity:1,
   total:10,
   price:10,
   desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
   website:"http://eloquentjavascript.ne/"
},
{  
  id: 4,
  titl: "Eloquent JavaScript, Second Edition",
  subtil: "A Modern Introduction to Programming",
  count:1,
  quantity:1,
  total:10,
  price:10,author: "Marijn Havereke"  ,
  description: "This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git experience.",

  published: "2014-12-14T00:00:00.000Z",
 publishr: "No Starch Press",
 pages:472,
 AddCartCondition:false,
 imagepath:process.env.PUBLIC_URL + '/book4.jpg',
urchse:false,
 count:1,
 quantity:1,
 total:10,
 price:10,
//  imgpath:process.env.PUBLIC_URL/+"book1.jpg",
 desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
 website:"http://eloquentjavascript.ne/"
},

{  
  id: 5,
  titl: "Eloquent JavaScript, Second Edition",
  subtil: "A Modern Introduction to Programming",
  count:1,
  quantity:1,
  total:10,
  price:10,author: "Marijn Havereke"  ,
  description: "This pocket guide is the perfect on-the-job companion to Git, the distributed version control system. It provides a compact, readable introduction to Git for new users, as well as a reference to common commands and procedures for those of you with Git experience.",

  published: "2014-12-14T00:00:00.000Z",
 publishr: "No Starch Press",
 pages:472,
 AddCartCondition:false,
 imagepath:process.env.PUBLIC_URL + '/book5.jpg',
 purchse:false,
 count:1,
 quantity:1,
 total:10,
 price:10,
 desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
 website:"http://eloquentjavascript.ne/"
}
,
{  
  id: 6,
  titl: "Eloquent JavaScript, Second Edition",
  subtitle: "A Modern Introduction to Programming",
  count:1,
  quantity:1,
  total:10,
  price:10,author: "Marijn Havereke"  ,
  description: "Design and build Web APIs for a broad range of clients—including browsers and mobile devices—that can adapt to change over time. This practical, hands-on guide takes you through the theory and tools you need to build evolvable HTTP services with Microsoft’s ASP.NET Web API framework. In the process, you’ll learn how design and implement a real-world Web API.",

  published: "2014-12-14T00:00:00.000Z",
 publishr: "No Starch Press",
 pages:472,
 AddCartCondition:false,
 imagepath:process.env.PUBLIC_URL + '/book6.jpg',
 purchse:false,
 count:1,
 quantity:1,
 total:10,
 price:10,
 desription: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
 website:"http://eloquentjavascript.ne/"
}
    ,
      {
        id: 7,
        titl: "Learning JavaScript Design Patterns",
        subtitle: "A JavaScript and jQuery Developer's Guide",
       author: "Addy Osmani",
       count:1,
       quantity:1,
       total:10,
       price:10,
       description: "Design and build Web APIs for a broad range of clients—including browsers and mobile devices—that can adapt to change over time. This practical, hands-on guide takes you through the theory and tools you need to build evolvable HTTP services with Microsoft’s ASP.NET Web API framework. In the process, you’ll learn how design and implement a real-world Web API.",

       blished: "2012-07-01T00:00:00.000Z",
        publisher: "O'Reilly Media",
        pages: 254,
        AddCartCondition:false,
        imagepath:process.env.PUBLIC_URL + '/book7.jpg',
        purchse:false,
        count:1,
        quantity:1,
        total:10,
        price:10,
        description: "With Learning JavaScript Design Patterns, you'll learn how to write beautiful, structured, and maintainable JavaScript by applying classical and modern design patterns to the language. If you want to keep your code efficient, more manageable, and up-to-date with the latest best practices, this book is for you.",
        website: "http://www.addyosmani.com/resources/essentialjsdesignpatterns/book/"
      },
      {
        id: 8,
        titl: "Speaking JavaScript",
        subtitle: "An In-Depth Guide o Programmers",
        author: "Axel Rauschmayer",
        description: "Design and build Web APIs for a broad range of clients—including browsers and mobile devices—that can adapt to change over time. This practical, hands-on guide takes you through the theory and tools you need to build evolvable HTTP services with Microsoft’s ASP.NET Web API framework. In the process, you’ll learn how design and implement a real-world Web API.",

    count:1,
    quantity:1,
    total:10,
    quantity:1,
    price:10,
        published: "2014-02-01T00:00:00.000",
        publisher: "O'Reilly Media",
        pages: 460,
        AddCartCondition:false,
        imagepath:process.env.PUBLIC_URL + '/book8.jpg',
        descripion: "Like it or not, JavaScript is everywhere these days-from browser to server to mobile-and now you, too, need to learn the language or dive deeper than you have. This concise book guidesyu into and through JavaScript, written by a veteran programmer who once found himself in the same position.",
        purche:false,
        count:1,
        quantity:1,
        total:10,
        price:10,
      website: "http://speakigjs.com"
      },
      {
        id: 9,
        titl: "Programming JavaScript Applications",
        subtitle: "Robust Web Architecture with Node, HTML5, and Modern JS Libraries",
        author :"Eric Elliott",
        count:1,
        quantity:1,
        total:10,
        price:10,
        description: "Design and build Web APIs for a broad range of clients—including browsers and mobile devices—that can adapt to change over time. This practical, hands-on guide takes you through the theory and tools you need to build evolvable HTTP services with Microsoft’s ASP.NET Web API framework. In the process, you’ll learn how design and implement a real-world Web API.",

        published: "2014-07-01T00:00:00.000Z",
        publisher: "O'Reilly Media",
        pages: 254,
        AddCartCondition:false,
        imagepath:process.env.PUBLIC_URL + '/book9.jpg',
        purchas:false,
        descrption: "Take advantage of JavaScript's power to build robust web-scale or enterprise applications that are easy to extend and maintain. By applying the design patterns outlined in this practical book, experienced JavaScript developers will learn how to write flexible and resilient code that's easier-yes, easier-to work with as your code base grows.",
        website: "ttp://chimera.labs.oreilly.com/books/1234000000262/index.htl"
    },
     
   ]



   export const Detail={
    author :"Marijn Haverbeke",
    count:1,
    quantity:1,
    total:10,
    price:10,
    description: "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.",
    id: 1,
    pages: 472,
    AddCartCondition:false,
    imagepath:process.env.PUBLIC_URL + '/book9.jpg',

    published: "2014-12-14T00:00:00.000Z",
    publisher: "O'Reilly Media",
    purchse: false,
    subtitle: "A Modern Introduction to Programming",
    title: "Eloquent JavaScript, Second Edition",
    website: "http://eloquentjavascript.net/"
    }